### ISSUE TITLE
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor

### ISSUE THREAD

**Issue by sudoLife** [autodistill/autodistill-owl-vit#4]
Hi, 

While following [this guide](https://roboflow.com/model/owl-vit), I get the error in the title. My code:
```python
from autodistill_owl_vit import OWLViT
from autodistill.detection import CaptionOntology
base_model = OWLViT(
    ontology=CaptionOntology(
        {
            "white strawberry in cream": "white strawberry",
            "red strawberry": "red strawberry"
        }
    )
)
result = base_model.predict("2544.jpg")
print(result)
```

Any ideas?

The error occurs here:
```
File "/home/sudolife/projects/yolo-world/venv/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
 ```

I might investigate further a little later, but the stack trace is quite deep so it'll take some time.

**Comment by sudoLife** [comment]
Okay, so that was because the model was put on the GPU while the same wasn't being done for the inputs. Fixed it.

**Comment by ArghyaChatterjee** [comment]
Still getting the issue, is there any fix for this ?? Looks like you haven't pushed the changes to this branch or updated the binaries being installed with pip install autodistill-owl-vit .

**Comment by sudoLife** [comment]
> Still getting the issue, is there any fix for this ?? Looks like you haven't pushed the changes to this branch or updated the binaries being installed with pip install autodistill-owl-vit .

Hi, I can't push the changes to the branch because I'm not the maintainer of the project. That being said, you can apply the pull request to your installed version and it should work :)
